### ISSUE TITLE
can't login in safari browser

### ISSUE THREAD

**Issue by mingqi** [photo/frontend#1574]
500 error was return when login on Safari browser. The browser will send a post request to /user/login URL. the behaviour is difference with Chrome and Firefox. Chrome and Firefox will first a request "login.json" uri.  

--------
[Sat Mar 28 10:34:04.893281 2015] [:error] [pid 32429] [client 123.123.6.234:53926] {severity:warn, description:"Uncaught exception (/var/www/openphoto/src/libraries/external/epi/EpiException.php:13): Could not find route /user/login from /user/login?r=/", additional:}, referer: http://mingqi.me/user/login?r=/

**Comment by jmathai** [comment]
Sounds like a JS error. Can you check the console of your browser to see if anything is causing problems?

**Comment by mingqi** [comment]
Yes. the problem is some js and css with googleapis.com domain was block by China's great firewall.
