### ISSUE TITLE
Several critical security vulnerabilities - looking for a contact

### ISSUE THREAD

**Issue by rverton** [photo/frontend#1599]
Hi,
who can I talk to about some critical vulnerabilities I found in Trovebox?

Greetings,
robin

**Comment by cedricbonhomme** [comment]
Hello,
I would be interested to get feedback from this.

thank you

**Comment by rverton** [comment]
Hi @cedricbonhomme,
I would prefer sending details of this to a core contributor.
Best Regards,
robin

**Comment by jmathai** [comment]
Hi @rverton, can you send it to jaisen at githubusername dot com?

**Comment by rverton** [comment]
Hi @jmathai,
thanks for responding. I just sent another email to this address, maybe it was marked as spam the last time.

**Comment by cedricbonhomme** [comment]
Hi @rverton ,
it is possible to have some news? At least by email
Thanks a lot!

**Comment by rverton** [comment]
HI @cedricbonhomme,
I'm in contact with @jmathai and his plan is to add the vulnerabilities as issues here and/or directly fix them.

**Comment by cedricbonhomme** [comment]
OK, thank you for the feedback!

**Comment by cedricbonhomme** [comment]
thank you! I'll have a look at the report.

**Comment by rverton** [comment]
Hi @cedricbonhomme,
looks like you are working on this now, so if you have any questions, feel free to contact me directly at hello at robinverton de.

**Comment by cedricbonhomme** [comment]
Hi @jmathai,
Do you will have some time soon to have a look at it (and also the PR)?
thanks,

**Comment by rverton** [comment]
Hi @jmathai, is there any update on this? The PR from cedric with the vulnerabilities is public, so it would be better to merge this sooner than later.
Thanks

**Comment by jmathai** [comment]
Sorry for the delay --- i reviewed the pr and added some comments.

**Comment by rverton** [comment]
Hi @jmathai, @cedricbonhomme ,
thanks to both of you for your time fixing this. I'll finish and publish the advisory soon.
Bests,
Robin
